included:
  - nose/Screens

disabled_rules:
  - trailing_whitespace
  - force_cast
  - identifier_name
  - cyclomatic_complexity

line_length:
  warning: 300
  error: 500

body_length:
  Warning: 300
  Error: 500

