included:
  - nose/Screens

disabled_rules:
  - trailing_whitespace
  - force_cast
  - identifier_name
  - cyclomatic_complexity

line_length:
  warning: 300
  error: 500

function_body_length:
  warning: 300
  error: 500

type_body_length:
  warning: 400
  error: 1000
