default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number

    build_app(
      scheme: "nose-staging",
      export_method: "app-store", # or "development" or "ad-hoc"
      export_options: {
        signingStyle: "automatic"
      }
    )

    upload_to_testflight
  end
end