name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

     - name: Install CocoaPods Dependencies
       run: pod install

      - name: Run SwiftLint
        run: swiftlint --fix

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -workspace YourApp.xcworkspace \
          -scheme YourApp \
          -destination 'platform=iOS Simulator,name=iPhone 18' \
          | xcpretty

      - name: Run UI Tests
        run: |
          xcodebuild test \
          -workspace YourApp.xcworkspace \
          -scheme YourApp \
          -destination 'platform=iOS Simulator,name=iPhone 18' \
          | xcpretty

      - name: Build and Archive
        run: |
          xcodebuild clean archive \
          -workspace YourApp.xcworkspace \
          -scheme YourApp \
          -destination 'generic/platform=iOS' \
          -archivePath $GITHUB_WORKSPACE/build/YourApp.xcarchive

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build/YourApp.xcarchive
